# Generated by Django 3.2 on 2021-05-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
