# Generated by Django 3.2.1 on 2021-05-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imageCaption',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='blog',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='teaser',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
